# -*- coding: utf-8 -*-
"""Arquivo Inicial - Minicurso Analise de Dados Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c332hxx_MoxgiCWquEJkN8QWiVPUYr13

# Desafio:

Você trabalha em uma grande empresa de Cartão de Crédito e o diretor da empresa percebeu que o número de clientes que cancelam seus cartões tem aumentado significativamente, causando prejuízos enormes para a empresa

O que fazer para evitar isso? Como saber as pessoas que têm maior tendência a cancelar o cartão?

# O que temos:

Temos 1 base de dados com informações dos clientes, tanto clientes atuais quanto clientes que cancelaram o cartão

Download da Base de Dados: Botão na página

Referência: https://www.kaggle.com/sakshigoyal7/credit-card-customers
"""

import pandas as pd
import plotly.express as px
from google.colab import files

table = pd.read_csv('/content/drive/MyDrive/MiniCurso Analise de Dados/ClientesBanco.csv', encoding="latin1")
table = table.drop('CLIENTNUM', axis=1)
display(table)



"""# Now let's handle empty values ​​and display a summary of the database columns."""

table = table.dropna()
display(table.info())

display(table.describe().round(1))

"""# Let's evaluate the division between Customers x Cancellations"""

qtd_categoria = table["Categoria"].value_counts()
display(qtd_categoria)
qtd_categoria_perc = table["Categoria"].value_counts(normalize=True).round(2)
display(qtd_categoria_perc)

"""# Finding out the reason for cancellations"""

for column in table:
  graphic = px.histogram(table, x=column, color="Categoria")
  graphic.show()

"""# The more products are contracted, the lower the chance of cancellation
- The higher the transaction amount, the lower are the chance of the card being cancelled.
- The more contacts the customer has made with the company, the greater the chance of canceling
"""

table.to_csv("Minicurso Analise de Dados Python.csv", index=False)
files.download("Minicurso Analise de Dados Python.csv")